### ISSUE TITLE
Invalid move in Duck chess

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#1051]
Smart AI reported on Discord
https://www.pychess.org/KJdVY3tK
```
28 Dec 2022 15:11:33.288518 <190>1 2022-12-28T14:11:33.160753+00:00 app web.1 - - ERROR:fairy:ERROR: sf.get_fen() failed on rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1 e2e4,e4f6,e7e6,e6e2,b1c3,c3e7,d7d5,d5h3,e4d5,d5d7,e6d5,d5e2,c3d5,d5d7,c7c6,c6b1,d5c3,c3e7,g8f6,f6b1,f1e2,e2e7,h7h5,h5d3,b2b3,b3b2,c8f5,f5b1,c1b2,b2e7,b8d7,d7a3,h2h3,h3e7,b7b5,b5c1,g1f3,f3b4,f8d6,d6b1,d2d4,d4b4,e8g8,g8d5,e1g1,g1b4,f8e8,e8d5,e2d3,d3e4,f5e6,e6b1,a2a4,a4b4,b5a4,a4b1,c3a4,a4f5,a8b8,b8b1,c2c4,c4c2,d6b4,b4b1 False
28 Dec 2022 15:11:33.288160 <190>1 2022-12-28T14:11:33.161007+00:00 app web.1 - - ERROR:game:ERROR: Exception in game KJdVY3tK play_move() d1c2,c2c2
28 Dec 2022 15:11:33.288130 <190>1 2022-12-28T14:11:33.161008+00:00 app web.1 - - ValueError: Invalid move 'd1c2,c2c2'
28 Dec 2022 15:11:33.28894 <190>1 2022-12-28T14:11:33.161008+00:00 app web.1 - -
28 Dec 2022 15:11:33.288162 <190>1 2022-12-28T14:11:33.161009+00:00 app web.1 - - The above exception was the direct cause of the following exception:
28 Dec 2022 15:11:33.28894 <190>1 2022-12-28T14:11:33.161009+00:00 app web.1 - -
28 Dec 2022 15:11:33.288128 <190>1 2022-12-28T14:11:33.161009+00:00 app web.1 - - Traceback (most recent call last):
  File "/app/server/game.py", line 340, in play_move
    self.board.push(move)
  File "/app/server/fairy.py", line 100, in push
    self.fen = sf.get_fen(
SystemError: <built-in function get_fen> returned a result with an exception set
```

**Comment by gbtami** [comment]
```
28 Dec 2022 15:12:45.139218 <190>1 2022-12-28T14:12:44.758926+00:00 app web.1 - - ERROR:fairy:ERROR: sf.get_fen() failed on rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1 c2c4,c4e3,e7e6,e6b5 False
28 Dec 2022 15:12:45.139160 <190>1 2022-12-28T14:12:44.759114+00:00 app web.1 - - ERROR:game:ERROR: Exception in game h7Mu4LZu play_move() b1c3,c3c3
28 Dec 2022 15:12:45.139130 <190>1 2022-12-28T14:12:44.759114+00:00 app web.1 - - ValueError: Invalid move 'b1c3,c3c3'
28 Dec 2022 15:12:45.13994 <190>1 2022-12-28T14:12:44.759115+00:00 app web.1 - -
28 Dec 2022 15:12:45.139162 <190>1 2022-12-28T14:12:44.759115+00:00 app web.1 - - The above exception was the direct cause of the following exception:
28 Dec 2022 15:12:45.13994 <190>1 2022-12-28T14:12:44.759115+00:00 app web.1 - -
28 Dec 2022 15:12:45.139128 <190>1 2022-12-28T14:12:44.759115+00:00 app web.1 - - Traceback (most recent call last):
  File "/app/server/game.py", line 340, in play_move
    self.board.push(move)
  File "/app/server/fairy.py", line 100, in push
    self.fen = sf.get_fen(
SystemError: <built-in function get_fen> returned a result with an exception set
```

**Comment by gbtami** [comment]
```
28 Dec 2022 01:01:57.191438 <190>1 2022-12-28T00:01:57.017187+00:00 app web.1 - - ERROR:fairy:ERROR: sf.get_fen() failed on rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1 d2d4,d4e6,d7d6,d6a3,c1f4,f4d7,g8f6,f6e3,g1f3,f3d7,f6d5,d5e3,f4g3,g3d7,b8c6,c6g1,e2e4,e4b4,d5f6,f6g1,e4e5,e5h5,d6e5,e5c3,d4e5,e5h5,f6e4,e4d5,f1c4,c4d7,e4g3,g3d5,h2g3,g3d7,e7e6,e6d4,b1c3,c3e7,a7a6,a6d3,f3g5,g5e7,c6e5,e5d3,c4b3,b3e7,e5f3,f3c1 False
28 Dec 2022 01:01:57.191160 <190>1 2022-12-28T00:01:57.017919+00:00 app web.1 - - ERROR:game:ERROR: Exception in game 1epRZspH play_move() d1d8,d8f3
28 Dec 2022 01:01:57.191129 <190>1 2022-12-28T00:01:57.01792+00:00 app web.1 - - ValueError: Invalid move 'd1d8,d8f3'
28 Dec 2022 01:01:57.19193 <190>1 2022-12-28T00:01:57.01792+00:00 app web.1 - -
28 Dec 2022 01:01:57.191162 <190>1 2022-12-28T00:01:57.017921+00:00 app web.1 - - The above exception was the direct cause of the following exception:
28 Dec 2022 01:01:57.19194 <190>1 2022-12-28T00:01:57.017921+00:00 app web.1 - -
28 Dec 2022 01:01:57.191128 <190>1 2022-12-28T00:01:57.017921+00:00 app web.1 - - Traceback (most recent call last):
  File "/app/server/game.py", line 340, in play_move
    self.board.push(move)
  File "/app/server/fairy.py", line 100, in push
    self.fen = sf.get_fen(
SystemError: <built-in function get_fen> returned a result with an exception set
```

**Comment by gbtami** [comment]
```
27 Dec 2022 10:58:33.757278 <190>1 2022-12-27T09:58:33.503534+00:00 app web.1 - - ERROR:fairy:ERROR: sf.get_fen() failed on rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1 e2e4,e4e6,f7f6,f6d5,e4e5,e5f7,b7b5,b5g4,e5f6,f6f7,e7e6,e6d4,f6g7,g7e7,c8a6,a6b7 False
27 Dec 2022 10:58:33.757160 <190>1 2022-12-27T09:58:33.506172+00:00 app web.1 - - ERROR:game:ERROR: Exception in game ELjfnWgr play_move() d1g4,g4h8
27 Dec 2022 10:58:33.757130 <190>1 2022-12-27T09:58:33.506174+00:00 app web.1 - - ValueError: Invalid move 'd1g4,g4h8'
27 Dec 2022 10:58:33.75794 <190>1 2022-12-27T09:58:33.506174+00:00 app web.1 - -
27 Dec 2022 10:58:33.757162 <190>1 2022-12-27T09:58:33.506174+00:00 app web.1 - - The above exception was the direct cause of the following exception:
27 Dec 2022 10:58:33.75794 <190>1 2022-12-27T09:58:33.506175+00:00 app web.1 - -
27 Dec 2022 10:58:33.757128 <190>1 2022-12-27T09:58:33.506175+00:00 app web.1 - - Traceback (most recent call last):
  File "/app/server/game.py", line 340, in play_move
    self.board.push(move)
  File "/app/server/fairy.py", line 100, in push
    self.fen = sf.get_fen(
SystemError: <built-in function get_fen> returned a result with an exception set
```
