### ISSUE TITLE
Invalid (castling) move in S-Chess

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#1065]
In game https://www.pychess.org/FmKP4n7b
![https://i.imgur.com/s0ZPrB5.png](https://i.imgur.com/s0ZPrB5.png)
```
12 Feb 2023 17:53:23.874275 <190>1 2023-02-12T16:53:23.596925+00:00 app web.1 - - ERROR:fairy:ERROR: sf.get_fen() failed on rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR[HEhe] w KQBCDFGkqbcdfg - 0 1 e2e4,b8c6,d2d4,e7e5,d4d5,c6d4,g1f3,d4f3,d1f3e,g8f6,f1d3,a7a6 False
12 Feb 2023 17:53:23.874155 <190>1 2023-02-12T16:53:23.598852+00:00 app web.1 - - ERROR:game:ERROR: Exception in game FmKP4n7b play_move() h1e1
12 Feb 2023 17:53:23.874125 <190>1 2023-02-12T16:53:23.598853+00:00 app web.1 - - ValueError: Invalid move 'h1e1'
12 Feb 2023 17:53:23.87494 <190>1 2023-02-12T16:53:23.598854+00:00 app web.1 - -
12 Feb 2023 17:53:23.874162 <190>1 2023-02-12T16:53:23.598854+00:00 app web.1 - - The above exception was the direct cause of the following exception:
12 Feb 2023 17:53:23.87494 <190>1 2023-02-12T16:53:23.598855+00:00 app web.1 - -
12 Feb 2023 17:53:23.874128 <190>1 2023-02-12T16:53:23.598855+00:00 app web.1 - - Traceback (most recent call last):
  File "/app/server/game.py", line 340, in play_move
    self.board.push(move)
  File "/app/server/fairy.py", line 100, in push
    self.fen = sf.get_fen(
               ^^^^^^^^^^^
SystemError: <built-in function get_fen> returned a result with an exception set
```

**Comment by gbtami** [comment]
Another case in https://www.pychess.org/kaQYaf9O
```
12 Feb 2023 18:10:25.482342 <190>1 2023-02-12T17:10:25.218842+00:00 app web.1 - - ERROR:fairy:ERROR: sf.get_fen() failed on rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR[HEhe] w KQBCDFGkqbcdfg - 0 1 e2e4,e7e5,g1f3h,b8c6,f1c4,g8f6,d2d3,f8c5,c1e3,c5e3,f2e3,d7d5,e4d5,f6d5,b1c3,c8e6h,c4b5,c8d6,b5c6,b7c6,c3e4,d6f5,d1d2e,f7f6,g1f2 False
12 Feb 2023 18:10:25.482155 <190>1 2023-02-12T17:10:25.219263+00:00 app web.1 - - ERROR:game:ERROR: Exception in game kaQYaf9O play_move() h8e8
12 Feb 2023 18:10:25.482125 <190>1 2023-02-12T17:10:25.219264+00:00 app web.1 - - ValueError: Invalid move 'h8e8'
12 Feb 2023 18:10:25.48294 <190>1 2023-02-12T17:10:25.219264+00:00 app web.1 - -
12 Feb 2023 18:10:25.482162 <190>1 2023-02-12T17:10:25.219265+00:00 app web.1 - - The above exception was the direct cause of the following exception:
12 Feb 2023 18:10:25.48294 <190>1 2023-02-12T17:10:25.219265+00:00 app web.1 - -
12 Feb 2023 18:10:25.482128 <190>1 2023-02-12T17:10:25.219265+00:00 app web.1 - - Traceback (most recent call last):
  File "/app/server/game.py", line 340, in play_move
    self.board.push(move)
  File "/app/server/fairy.py", line 100, in push
    self.fen = sf.get_fen(
               ^^^^^^^^^^^
SystemError: <built-in function get_fen> returned a result with an exception set
```

**Comment by gbtami** [comment]
Additional info from @mattgatto (darken)
"Last one tried to drag king to kingside castle landing square king would be on after successful castle"
"Playing on Android tablet, Samsung Galaxy Tab A (8.0", 2019), Android 11, Google Chrome 109"

**Comment by gbtami** [comment]
@Fulmene any idea?

**Comment by Fulmene** [comment]
I tried reproducing it today. Found nothing still. Does darken still encounter this bug?

**Comment by gbtami** [comment]
Idk. I'll try to drag him here :)

**Comment by mattgatto** [comment]
Hi! Yes, last s-chess I played in, (2 weeks ago~) I was experiencing it.

pychess.org doesn't seem to like my old and somewhat outdated Android
tablet Google Chrome browser.

**Comment by mattgatto** [comment]
Last S-Chess tournament I played in, that is.

**Comment by Fulmene** [comment]
I've always tried to reproduce it by dragging. No wonder I haven't found anything. 😂

If that is the actual reason I'll probably figure out what to do by tomorrow.
