### ISSUE TITLE
Bughouse960 invalid move

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#1617]
https://pychess-variants-dev.onrender.com/7p4b6eKs
```
ERROR: Exception in game 7p4b6eKs play_move() c8a8
ValueError: Invalid move 'c8a8'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/render/project/src/server/bug/game_bug.py", line 210, in play_move
    last_move_captured_role = self.boards[board].piece_to_partner(move)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/server/fairy.py", line 206, in piece_to_partner
    return sf.piece_to_partner(self.variant, self.fen, [move])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemError: <built-in function piece_to_partner> returned a result with an exception set```

**Comment by gbtami** [comment]
Seems the latest parameter (chess960) is missing here
https://github.com/gbtami/pychess-variants/blob/master/server/fairy.py#L206
