### ISSUE TITLE
Invalid move in Embassy game

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#1708]
Atlas999 reported on Discord:
https://www.pychess.org/9bOkVH91
![https://imgur.com/rmAh4o5.png](https://imgur.com/rmAh4o5.png)

**Comment by gbtami** [comment]
In game https://www.pychess.org/rog2PAsU?ply=29 possible O-O-O (e8h8) happened, because fairyfishnet worker crashed.
```
><> 1: DEBUG: Got job: {"work": {"type": "move", "id": "RQ4fLz", "level": 0}, "time": 1159510.209854696, "game_id": "rog2PAsU", "position": "rnbqkcabnr/pppppppppp/10/10/10/10/PPPPPPPPPP/RNBQKCABNR w KQkq - 0 1", "variant": "capablanca", "chess960": false, "moves": "g2g4 i8h6 e2e3 f7f5 g4f5 h6f5 h1g2 f5h4 d2d4 h4g2 e1d2 g2h4 d1h5 g7g6 h5h4 h8f6 h4f4 h7h6 g1e2 f6g5 f4i4 h6h5 i4j3 b8c6 b1c3 f8f7 i1h3 g8h7 d4d5 e8h8", "nnue": false}
><> 1: DEBUG: Playing https://pychess-variants.herokuapp.com/rog2PAsU (capablanca) with lvl 0
><> 1: ENGINE: 64699 << setoption name UCI_Chess960 value false
><> 1: ENGINE: 64699 << setoption name UCI_Variant value capablanca
><> 1: ENGINE: 64699 << setoption name Skill Level value -4
><> 1: ENGINE: 64699 << setoption name UCI_AnalyseMode value false
><> 1: ENGINE: 64699 << ucinewgame
><> 1: ENGINE: 64699 << isready
><> 1: ENGINE: 64699 >> readyok
><> 1: ENGINE: 64699 << position fen rnbqkcabnr/pppppppppp/10/10/10/10/PPPPPPPPPP/RNBQKCABNR w KQkq - 0 1 moves g2g4 i8h6 e2e3 f7f5 g4f5 h6f5 h1g2 f5h4 d2d4 h4g2 e1d2 g2h4 d1h5 g7g6 h5h4 h8f6 h4f4 h7h6 g1e2 f6g5 f4i4 h6h5 i4j3 b8c6 b1c3 f8f7 i1h3 g8h7 d4d5 e8h8
><> 1: ENGINE: 64699 << go movetime 17 depth 1
><> 1: ENGINE: 64699 >> info string classical evaluation enabled
><> 1: ENGINE: 64699 >> info depth 1 seldepth 1 multipv 1 score cp 91 nodes 1924 nps 641333 tbhits 0 time 3 pv c6e5
><> 1: ENGINE: 64699 >> bestmove c6a5 ponder h3g5
><> 1: ERROR: Fatal error in worker
ValueError: Invalid move 'e8h8'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tamas/.local/lib/python3.8/site-packages/fairyfishnet.py", line 720, in run
    self.run_inner()
  File "/home/tamas/.local/lib/python3.8/site-packages/fairyfishnet.py", line 735, in run_inner
    path, request = self.work()
  File "/home/tamas/.local/lib/python3.8/site-packages/fairyfishnet.py", line 877, in work
    result = self.bestmove(self.job)
  File "/home/tamas/.local/lib/python3.8/site-packages/fairyfishnet.py", line 939, in bestmove
    fen = sf.get_fen(variant, fen, moves, chess960, sfen, show_promoted)
SystemError: <built-in function get_fen> returned a result with an error set
ValueError: Invalid move 'e8h8'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tamas/.local/lib/python3.8/site-packages/fairyfishnet.py", line 2515, in <module>
    sys.exit(main(sys.argv))
  File "/home/tamas/.local/lib/python3.8/site-packages/fairyfishnet.py", line 2499, in main
    sys.exit(commands[args.command](args))
  File "/home/tamas/.local/lib/python3.8/site-packages/fairyfishnet.py", line 1784, in cmd_run
    raise worker.fatal_error
  File "/home/tamas/.local/lib/python3.8/site-packages/fairyfishnet.py", line 720, in run
    self.run_inner()
  File "/home/tamas/.local/lib/python3.8/site-packages/fairyfishnet.py", line 735, in run_inner
    path, request = self.work()
  File "/home/tamas/.local/lib/python3.8/site-packages/fairyfishnet.py", line 877, in work
    result = self.bestmove(self.job)
  File "/home/tamas/.local/lib/python3.8/site-packages/fairyfishnet.py", line 939, in bestmove
    fen = sf.get_fen(variant, fen, moves, chess960, sfen, show_promoted)
SystemError: <built-in function get_fen> returned a result with an error set
tamas@tami-T540p:~/fairyfishnet$ 
```
