### ISSUE TITLE
Invalid move when all moves premoved fast

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#305]
In game https://www.pychess.org/q3y3xgs6
```
Jul 31 01:21:55 pychess-variants app/web.1 ERROR:fairy:ERROR: sf.get_fen() failed on 8/8/4pppp/pppp4/4PPPP/PPPP4/8/8[KFRRSSNNkfrrssnn] w - - 0 1 F@e3,N@c6,N@f3 False
Jul 31 01:21:55 pychess-variants app/web.1 ERROR:game:ERROR: Exception in game q3y3xgs6 play_move() S@g3
Jul 31 01:21:55 pychess-variants app/web.1 ValueError: Invalid move 'S@g3'
Jul 31 01:21:55 pychess-variants app/web.1
Jul 31 01:21:55 pychess-variants app/web.1 The above exception was the direct cause of the following exception:
Jul 31 01:21:55 pychess-variants app/web.1
Jul 31 01:21:55 pychess-variants app/web.1 Traceback (most recent call last):
Jul 31 01:21:55 pychess-variants app/web.1   File "/app/server/game.py", line 250, in play_move
Jul 31 01:21:55 pychess-variants app/web.1     self.board.push(move)
Jul 31 01:21:55 pychess-variants app/web.1   File "/app/server/fairy.py", line 52, in push
Jul 31 01:21:55 pychess-variants app/web.1     self.fen = sf.get_fen(self.variant, self.fen, [move], self.chess960, self.sfen, self.show_promoted, self.count_started)
Jul 31 01:21:55 pychess-variants app/web.1 SystemError: <built-in function get_fen> returned a result with an error set
Jul 31 01:22:13 pychess-variants app/web.1 wplayer Entitled_Untitled game socket closed
```

**Comment by gbtami** [comment]
Fixed via https://github.com/gbtami/pychess-variants/commit/b25ad14589bf07dff521b6ef13e9daa7984b4ca3
