### ISSUE TITLE
500 Error on connection to self-installed server

### ISSUE THREAD

**Issue by green-teal** [gbtami/pychess-variants#325]
After cloning the repo into an Ubuntu container and following the setup instructions, I attempted to connect to the server and got a 500 error.

Server log:

~~~~
# python3 server/server.py
Variant 'grandhouse' already exists.
Variant 'gothhouse' already exists.
Variant 'shogun' already exists.
Variant 'orda' already exists.
Variant 'synochess' already exists.
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/helpers.py", line 391, in __get__
    return inst._cache[self.name]
KeyError: 'cookies'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/local/lib/python3.8/dist-packages/aiohttp_session/__init__.py", line 154, in factory
    response = await handler(request)
  File "/root/pychess-variants/server/index.py", line 43, in index
    session = await aiohttp_session.get_session(request)
  File "/usr/local/lib/python3.8/dist-packages/aiohttp_session/__init__.py", line 118, in get_session
    session = await storage.load_session(request)
  File "/usr/local/lib/python3.8/dist-packages/aiohttp_session/cookie_storage.py", line 31, in load_session
    cookie = self.load_cookie(request)
  File "/usr/local/lib/python3.8/dist-packages/aiohttp_session/__init__.py", line 234, in load_cookie
    cookie = request.cookies.get(self._cookie_name)
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/helpers.py", line 393, in __get__
    val = self.wrapped(inst)
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/web_request.py", line 482, in cookies
    parsed = SimpleCookie(raw)
  File "/usr/lib/python3.8/http/cookies.py", line 480, in __init__
    self.load(input)
  File "/usr/lib/python3.8/http/cookies.py", line 529, in load
    self.__parse_string(rawdata)
  File "/usr/lib/python3.8/http/cookies.py", line 593, in __parse_string
    self.__set(key, rval, cval)
  File "/usr/lib/python3.8/http/cookies.py", line 485, in __set
    M.set(key, real_value, coded_value)
  File "/usr/lib/python3.8/http/cookies.py", line 352, in set
    raise CookieError('Illegal key %r' % (key,))
http.cookies.CookieError: Illegal key 'ys-api/dvr/entry/grid_upcoming'
INFO:aiohttp.access:127.0.0.1 [02/Sep/2020:22:19:26 +0000] "GET / HTTP/1.1" 500 334 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0"
~~~~

Details of installed software are as follows:

~~~~
`# mongo --version
MongoDB shell version v3.6.8
git version: 8e540c0b6db93ce994cc548f000900bdc740f80a
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
allocator: tcmalloc
modules: none
build environment:
    distarch: x86_64
    target_arch: x86_64

# gulp --version
CLI version: 2.3.0
Local version: 4.0.2

# yarn --version
1.22.5

# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

# pip3 show aiohttp
Name: aiohttp
Version: 3.6.2

# python3 --version
Python 3.8.2
~~~~

Any ideas? Thanks!

**Comment by green-teal** [comment]
I found the issue.

My browser had a saved cookie with key 'ys-api/dvr/entry/grid_upcoming' from another service I had run in a container on the same server.

The address was the same so my browser sent this cookie to pychess-variants, and due to aio's strict handling of invalid cookie names, it resulted in a 500 error.

I'll close this.
