### ISSUE TITLE
Invalid move in Shinobi game

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#507]
https://www.pychess.org/I2FLqZ5P
```
2021-04-23T08:10:31.828315+00:00 app[web.1]: db insert game result 'I2FLqZ5P'
2021-04-23T08:10:48.527857+00:00 app[web.1]: ERROR:fairy:ERROR: sf.get_fen() failed on rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/LH1CK1HL[LHMMDJ] w kq - 0 1 J@c3,d7d5,L@d3,g8f6,H@e4,e7e6,e4f6,d8f6,D@f3,f6c3,b1c3,f8c5 False
2021-04-23T08:10:48.528806+00:00 app[web.1]: ERROR:game:ERROR: Exception in game I2FLqZ5P play_move() c2c3
2021-04-23T08:10:48.528808+00:00 app[web.1]: ValueError: Invalid move 'c2c3'
2021-04-23T08:10:48.528808+00:00 app[web.1]: 
2021-04-23T08:10:48.528809+00:00 app[web.1]: The above exception was the direct cause of the following exception:
2021-04-23T08:10:48.528809+00:00 app[web.1]: 
2021-04-23T08:10:48.528810+00:00 app[web.1]: Traceback (most recent call last):
2021-04-23T08:10:48.528811+00:00 app[web.1]: File "/app/server/game.py", line 260, in play_move
2021-04-23T08:10:48.528811+00:00 app[web.1]: self.board.push(move)
2021-04-23T08:10:48.528811+00:00 app[web.1]: File "/app/server/fairy.py", line 51, in push
2021-04-23T08:10:48.528813+00:00 app[web.1]: self.fen = sf.get_fen(self.variant, self.fen, [move], self.chess960, self.sfen, self.show_promoted, self.count_started)
2021-04-23T08:10:48.528813+00:00 app[web.1]: SystemError: <built-in function get_fen> returned a result with an error set
```

**Comment by gbtami** [comment]
One worker was running old fairyfishnet version.
