### ISSUE TITLE
Game end by invalid move in Sittuyin tournament

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#703]
Both are in place pawn promotion.
https://www.pychess.org/ron8n8NK
https://www.pychess.org/V5EACLhU

**Comment by gbtami** [comment]
Server log for first game:
```
2021-11-20` 12:15:20.984 [pychess_variants] web.1   File "/app/server/game.py", line 281, in play_move
2021-11-20 12:15:20.984 [pychess_variants] web.1     self.fen = sf.get_fen(self.variant, self.fen, [move], self.chess960, self.sfen, self.show_promoted, self.count_started)
2021-11-20 12:15:20.984 [pychess_variants] web.1 Traceback (most recent call last):
2021-11-20 12:15:20.984 [pychess_variants] web.1
2021-11-20 12:15:20.984 [pychess_variants] web.1 The above exception was the direct cause of the following exception:
2021-11-20 12:15:20.984 [pychess_variants] web.1 ERROR:game:ERROR: Exception in game ron8n8NK play_move() e5e5f
2021-11-20 12:15:20.984 [pychess_variants] web.1     self.board.push(move)
2021-11-20 12:15:20.984 [pychess_variants] web.1 ValueError: Invalid move 'e5e5f'
2021-11-20 12:15:20.984 [pychess_variants] web.1   File "/app/server/fairy.py", line 62, in push
2021-11-20 12:15:20.984 [pychess_variants] web.1 SystemError: <built-in function get_fen> returned a result with an error set
2021-11-20 12:15:20.984 [pychess_variants] web.1 ERROR:fairy:ERROR: sf.get_fen() failed on 8/8/4pppp/pppp4/4PPPP/PPPP4/8/8[KFRRSSNNkfrrssnn] w - - 0 1 F@e3,N@e7,N@f3,F@d6,N@g3,N@f7,S@b2,S@c6,S@c2,S@d7,K@b1,K@c7,R@c1,R@h8,R@d1,R@b8,d3d4,d5e4,g3e4,f6f5,e4f6,e7d5,f6d5,c6d5,d4c5,d6c5,e3d4,f5g4,f3e5,f7e5,f4e5,d7c6,d4c5,c6c5,e5e5f False
```

**Comment by gbtami** [comment]
e5e5f is the last item in move_stack already when it arrives again. Seems double click in place promotion sometimes sends the move two times to the server somehow. @Fulmene any idea?

**Comment by Fulmene** [comment]
Reproduced by double-clicking on the newly promoted ferz after an in-place promotion. Seems to be what happened in the [Karavas game](https://youtu.be/12Nl5Ob3WDg?t=2321) too.

Looking at the [relevant code](https://github.com/gbtami/pychess-variants/blob/master/client/roundCtrl.ts#L1210-L1224), I think the problem is in the condition. After a move is sent, the `chessground.state.movable.dests` is still the same as before the promotion, so it re-sends the move when that square is double-clicked again.

Adding a condition that this double-clicking gesture is only available on the player's own turn should fix the problem.

**Comment by Fulmene** [comment]
![image](https://user-images.githubusercontent.com/13796147/142914316-c30dd139-b990-48b3-b3dc-7b58ac93ec9b.png)
Well, the dests still show up in this case. I'm feeling that we need to do something special to clear up chessground's internal state.

**Comment by gbtami** [comment]
Thx!

**Comment by gbtami** [comment]
Btw, shouldn't this fix needed in analysisCtrl.ts as well?

**Comment by Fulmene** [comment]
Well, yes, but analysisCtrl doesn't even use double-click right now. I didn't want to copy-paste the code, so I just left it like that to wait for refactoring. This bug is only dangerous in roundCtrl anyway.
